CREATE PROCEDURE FI_SP_AdicionaBeneficiario
    @CPF       VARCHAR(11),
    @NOME      VARCHAR(50),
    @IDCLIENTE BIGINT
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO BENEFICIARIOS (CPF, NOME, IDCLIENTE)
    VALUES (@CPF, @NOME, @IDCLIENTE);
END;
GO